name: Dependency Submission

on:
  push:
    branches:
      - main

jobs:
  security_check:
    runs-on: ubuntu-latest
    steps:
      - name: Maven Dependency Submission
        uses: advanced-security/maven-dependency-submission-action@v3.0.2
        with:
          token: ${{ secrets.PAT }}

