name: Dependency Submission

on:
  push:
    branches:
      - main
      
permissions:
  contents: write

jobs:
  dependencies_submit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Maven Dependency Submission
        uses: advanced-security/maven-dependency-submission-action@v3.0.2
